common: &common
  adapter: postgresql
  username: lilan 
  password:  sizzler3 

development:
  <<: *common
  database: devise-rspec-cucumber
  host: localhost
  port: 5432

test:
  <<: *common
  database: devise-rspec-cucumber

production:
  <<: *common
  database: devise-rspec-cucumber